{% set name = "s3cmd" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 966b0a494a916fc3b4324de38f089c86c70ee90e8e1cae6d59102103a4c0cc03

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - python-magic

test:
  commands:
    - s3cmd --help

about:
  home: https://s3tools.org/s3cmd
  license: GPL v2
  license_family: GPL
  license_file: LICENSE
  summary: Command line tool for managing Amazon S3 and CloudFront services
  description: |
    S3cmd is a free command line tool and client for uploading, retrieving and
    managing data in Amazon S3 and other cloud storage service providers that
    use the S3 protocol, such as Google Cloud Storage or DreamHost DreamObjects.
    It is best suited for power users who are familiar with command line programs.
    It is also ideal for batch scripts and automated backup to S3, triggered from
    cron, etc.
  doc_url: https://s3tools.org/usage
  dev_url: https://github.com/s3tools/s3cmd

extra:
  recipe-maintainers:
    - scopatz
